variables:
  AWS_ACCESS_KEY_ID: "${s3_access_key_id}"
  AWS_SECRET_ACCESS_KEY: "${s3_secret_access_key}"
  AWS_DISTRIBUTION_ID: "E12SRK9Q9NVFYC"
  AWS_S3_BUCKET: "s3://appguardian/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - public

stages:
  - package
  - upload

# Package
Package:
  stage: package
  image: node:16-alpine
  before_script:
    - apk add --no-cache python3 py3-pip make gcc g++
  script:
    - npm ci
    - npm run build
  only:
    - web

Upload S3:
  stage: upload
  image:
    name: amazon/aws-cli:2.7.2
    entrypoint: [""]
  script:
    - aws s3 rm $AWS_S3_BUCKET --recursive
    - aws s3 cp public/ $AWS_S3_BUCKET --recursive
    # - aws cloudfront create-invalidation --distribution-id $AWS_DISTRIBUTION_ID --paths "/*"
  only:
    - web
