variables:
  AWS_ACCESS_KEY_ID: "${s3_access_key_id}"
  AWS_SECRET_ACCESS_KEY: "${s3_secret_access_key}"
  AWS_DISTRIBUTION_ID: "E11TTMPGHORI0M"
  AWS_S3_BUCKET: "s3://appguardian/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - dist

stages:
  - package
  - upload

# Package
Package:
  stage: package
  image: node:20-alpine
  script:
    - npm config set proxy "http://${CODE_PROXY_HOST}"
    - npm config set https-proxy "http://${CODE_PROXY_HOST}"
    - npm config set strict-ssl false
    - npm ci
    - npm run build:release
  only:
    - web

Upload S3:
  stage: upload
  image:
    name: amazon/aws-cli:2.15.30
    entrypoint: [""]
  script:
    - aws s3 rm $AWS_S3_BUCKET --recursive
    - aws s3 cp dist/ $AWS_S3_BUCKET --recursive
    - aws cloudfront create-invalidation --distribution-id $AWS_DISTRIBUTION_ID --paths "/*"
  tags:
    - AWS_OPTIN
  only:
    - web
