variables:
  HTTP_PROXY: "http://194.145.60.1:9400"
  HTTPS_PROXY: "http://194.145.60.1:9400"
  NO_PROXY: 127.0.0.1,localhost,.siemens.de,.siemens.net,.siemens.io,.siemens.com
  AWS_ACCESS_KEY_ID: "${s3_access_key_id}"
  AWS_SECRET_ACCESS_KEY: "${s3_secret_access_key}"
  AWS_DISTRIBUTION_ID: "E11TTMPGHORI0M"
  AWS_S3_BUCKET: "s3://appguardian/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - dist

stages:
  - package
  - upload

# Package
Package:
  stage: package
  image: node:20-alpine
  before_script:
    - npm config set proxy ${HTTP_PROXY}
    - npm config set https-proxy ${HTTPS_PROXY}
    - npm config set strict-ssl false
  script:
    - npm install
    - npm run build:release
  only:
    - web

Upload S3:
  stage: upload
  image:
    name: amazon/aws-cli:2.15.30
    entrypoint: [""]
  script:
    - aws s3 rm $AWS_S3_BUCKET --recursive
    - aws s3 cp dist/ $AWS_S3_BUCKET --recursive
    - aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/*"
  only:
    - web
